stages:
  - build
  - lint

Server lint:
    image: registry.gitlab.com/jigsawcorp/log3900/server-ci
    cache:
      paths:
        - /go
    stage: lint
    script:
        - cd Server && make lint
    only:
        - master
        - release
Sever build:
    image: registry.gitlab.com/jigsawcorp/log3900/server-ci
    cache:
      paths:
        - /go
    stage: build
    script:
        - cd Server && make build
    only:
        - master
        - release