stages:
  - build
  - lint

Server lint:
    image: log3900.azurecr.io/server-ci:latest
    cache:
      paths:
        - /go/
    stage: lint
    script:
        - cd Server && make lint
    only:
        - master
        - release
Sever build:
    image: log3900.azurecr.io/server-ci:latest
    cache:
      paths:
        - /go/
    stage: build
    script:
        - cd Server && make build
    only:
        - master
        - release