stages:
  - build
  - lint
  - package

Server lint:
  image: registry.gitlab.com/jigsawcorp/log3900/server-ci
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .go
  stage: lint
  script:
    - export GOPATH="$CI_PROJECT_DIR/.go"
    - cp -r /go $GOPATH 
    - cd Server && make lint
  only:
    refs:
      - master
      - release
      - dev-server
    changes:
      - Server/**/*

Server build:
  image: registry.gitlab.com/jigsawcorp/log3900/server-ci
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .go
  stage: build
  script:
    - export GOPATH="$CI_PROJECT_DIR/.go"
    - cp -r /go $GOPATH 
    - cd Server && make build-linux
  only:
    refs:
      - master
      - release
      - dev-server
    changes:
      - Server/**/*
  artifacts:
    paths:
      - Server/dist/
    expire_in: 1 week

Server package DEV:
  tags:
    - shell
  stage: package
  script:
    - cd Server && make package
  only:
    refs:
      - dev-server
    changes:
      - Server/**/*

Server package PROD:
  tags:
    - shell
  stage: package
  script:
    - export RELEASE=True
    - cd Server && make package
  only:
    refs:
      - master
      - release
    changes:
      - Server/**/*
