stages:
  - build
  - lint
  - package
  - deploy

Server lint:
  image: registry.gitlab.com/jigsawcorp/log3900/server-ci
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .go
  stage: lint
  script:
    - export GOPATH="$CI_PROJECT_DIR/.go"
    - cp -r /go $GOPATH 
    - cd Server && make lint
  only:
      - master
      - release
      - dev-server

Server build:
  image: registry.gitlab.com/jigsawcorp/log3900/server-ci
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .go
  stage: build
  script:
    - export GOPATH="$CI_PROJECT_DIR/.go"
    - cp -r /go $GOPATH 
    - cd Server && make build-linux
  only:
    - master
    - release
    - dev-server
  artifacts:
    paths:
      - Server/dist/
    expire_in: 1 week

Server package:
  tags:
    - shell
  stage: package
  script:
    - cd Server && make package
  only:
    - master
    - release
    - dev-server
