version: "3"
services:
  log3900-prod:
    container_name: goserver-prod
    image: registry.gitlab.com/jigsawcorp/log3900/server:latest
    depends_on:
      - "postgres-prod"
      - "redis-prod"
    ports:
      - 5000:3000/tcp
      - 5001:3001/tcp
    volumes:
      - ./config/:/etc/polydraw/:ro
      - image-data:/data/
    restart: always

  postgres-prod:
    container_name: postgres-prod
    image: postgres
    expose:
      - 5432/tcp
    environment:
      - POSTGRES_PASSWORD=123456
    volumes:
      - db-data:/var/lib/postgresql/data

  redis-prod:
    container_name: redis-prod
    image: redis
    expose:
      - 6379/tcp
    volumes:
      - redis-data:/data

volumes:
  image-data:
  db-data:
  redis-data: