# Example configuration file for the server

# The config file can be located in the following paths
# - ./config.yaml
# - $HOME/.polydraw/config.yaml
# - /etc/polydraw/config.yaml

database:
    engine: sqlite3
    connection: ":memory:"
rest:
    port: 3000
    address: 127.0.0.1
socket:
    port: 3001
    address: 127.0.0.1